/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * $ID: $
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved$
 */
#ifndef __CDK_CONFIG_ARCHS_H__
#define __CDK_CONFIG_ARCHS_H__

/*
 * This file defines the chip architectures currently installed.
 */

#ifndef CDK_CONFIG_ARCH_XGS_INSTALLED
#define CDK_CONFIG_ARCH_XGS_INSTALLED
#endif

#ifndef CDK_CONFIG_ARCH_XGSM_INSTALLED
#define CDK_CONFIG_ARCH_XGSM_INSTALLED
#endif

#ifndef CDK_CONFIG_ARCH_ROBO_INSTALLED
#define CDK_CONFIG_ARCH_ROBO_INSTALLED
#endif

#ifndef CDK_CONFIG_ARCH_XGSD_INSTALLED
#define CDK_CONFIG_ARCH_XGSD_INSTALLED
#endif

#endif /* __CDK_CONFIG_ARCHS_H__ */

