/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * $ID: $
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved$
 */

/*
 * This file contains the necessary definitions for inclusion of
 * all internal PHY drivers for a specified set of switch chips.
 *
 * This file can be used to simplify the task of minimizing the
 * driver foot print. Note that the list of externel PHY drivers
 * to include depends on the hardware design and must be done 
 * manually.
 */
#ifndef __CDK_CONFIG_PHYS_H__
#define __CDK_CONFIG_PHYS_H__

#include "cdk_config.h"

/*
 * Avenger integrated PHYs
 */
#ifndef PHY_CONFIG_INCLUDE_BCMGPHY
#define PHY_CONFIG_INCLUDE_BCMGPHY 1
#endif
/*
 * Avenger Serdes
 */
#ifndef PHY_CONFIG_INCLUDE_BCMI_VIPER_XGXS
#define PHY_CONFIG_INCLUDE_BCMI_VIPER_XGXS 1
#endif
#ifndef PHY_CONFIG_INCLUDE_BCMI_TSCE_XGXS
#define PHY_CONFIG_INCLUDE_BCMI_TSCE_XGXS 1
#endif

#endif 

