/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * $ID: $
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-rsdk/master/Legal/LICENSE file.
 *
 * $Copyright: (c) 2020 Broadcom Inc.
 * All Rights Reserved$
 */

/*
 * Chip inclusion and exclusion support within the CDK can be
 * specified as a combination of the following defines:
 * 
 *     (1) #define CDK_CONFIG_INCLUDE_<CHIPNAME> [1|0]
 *             -- Include or exclude all revisions of the given device
 *             Example: #define CDK_CONFIG_INCLUDE_BCM5690   1
 * 
 *     (2) #define CDK_CONFIG_INCLUDE_<CHIPNAME>_<REV>X [1|0]
 *             -- Include or exclude all versions of the given revision
 *             Example: #define CDK_CONFIG_INCLUDE_BCM5690_Ax 0
 *                      #define CDK_CONFIG_INCLUde_BCM5690_Bx 1
 * 
 *     (3) #define CDK_CONFIG_INCLUDE_<EXACT_CHIP> [1|0]
 *             -- Include or exclude an exact device
 *             Example: #define CDK_CONFIG_INCLUDE_BCM5690_A0 1
 *                      #define CDK_CONFIG_INCLUDE_BCM5690_A1 0
 * 
 * 
 * The value of CDK_CONFIG_INCLUDE_CHIP_DEFAULT is used for any chips which
 * are left unspecified. Set this value to 1 or 0 to include or exclude all
 * chips by default.
 */
#ifndef __CDK_CONFIG_CHIPS_H__
#define __CDK_CONFIG_CHIPS_H__

#include "cdk_config_archs.h"

/* This determines whether a chip is included or excluded by default */
#ifndef CDK_CONFIG_INCLUDE_CHIP_DEFAULT
#define CDK_CONFIG_INCLUDE_CHIP_DEFAULT 1
#endif
#endif

