/*
 *         
 * $Id: phymod.xml,v 1.1.2.5 2013/09/12 10:43:06 nirf Exp $
 * 
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-rsdk/master/Legal/LICENSE file.
 *
 * $Copyright: 
 * All Rights Reserved.$
 *         
 *     
 * DO NOT EDIT THIS FILE!
 *
 */

#ifndef _EAGLE_COMMON_H__H_
#define _EAGLE_COMMON_H__H_

#include <phymod/phymod.h>

/* Translate eagle osr_mode register value to phymod enum*/
int eagle_osr_mode_to_enum(int osr_mode, phymod_osr_mode_t* osr_mode_en);

#endif /*_EAGLE_COMMON_H__H_*/
