/*
 * $Id: $
 * 
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __SHR_BSLENUM_H__
#define __SHR_BSLENUM_H__

typedef enum bsl_severity_e {
    bslSeverityOff            = 0,
    bslSeverityFatal          = 1,
    bslSeverityError          = 2,
    bslSeverityWarn           = 3,
    bslSeverityInfo           = 4,
    bslSeverityVerbose        = 5,
    bslSeverityDebug          = 6,
    bslSeverityNormal         = bslSeverityInfo,
    bslSeverityCount          = 7
} bsl_severity_t;

#define BSL_SEVERITY_NAMES_INIT { \
    "Off", \
    "Fatal", \
    "Error", \
    "Warn", \
    "Info", \
    "Verbose", \
    "Debug" \
}

typedef enum bsl_layer_e {
    bslLayerAppl              = 0,
    bslLayerFsal              = 1,
    bslLayerSal               = 2,
    bslLayerSoc               = 3,
    bslLayerCount             = 4
} bsl_layer_t;

#define BSL_LAYER_NAMES_INIT { \
    "APPL", \
    "FSAL", \
    "SAL", \
    "SOC"  \
}

typedef enum bsl_source_e {
    bslSourceAuth             = 0,
    bslSourceCfp              = 1,
    bslSourceCommon           = 2,
    bslSourceCosq             = 3,
    bslSourceCounter          = 4,
    bslSourceCral             = 5,
    bslSourceL2               = 6,
    bslSourceLag              = 7,
    bslSourceLink             = 8,
    bslSourceMcast            = 9,
    bslSourceMeter            = 10,
    bslSourceMirror           = 11,
    bslSourceOther            = 12,
    bslSourcePci              = 13,
    bslSourcePktio            = 14,
    bslSourcePort             = 15,
    bslSourceReg              = 16,
    bslSourceRstp             = 17,
    bslSourceSnoop            = 18,
    bslSourceStat             = 19,
    bslSourceStg              = 20,
    bslSourceSwitch           = 21,
    bslSourceVlan             = 22,
    bslSourceCount            = 23
} bsl_source_t;

#define BSL_SOURCE_NAMES_INIT { \
    "AUTH", \
    "CFP", \
    "COMMON", \
    "COSQ", \
    "CounTeR", \
    "CRAL", \
    "L2", \
    "LAG", \
    "LINK", \
    "MCAST", \
    "METER", \
    "MIRROR", \
    "OTHER", \
    "PCI", \
    "PKTIO", \
    "PORT", \
    "REG", \
    "RSTP", \
    "SNOOP", \
    "STAT", \
    "STG", \
    "SWITCH", \
    "VLAN"  \
}

/* Short hand macros for Appl layer */
#define BSL_APPL_RSTP                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceRstp
#define BSL_APPL_SNOOP                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerAppl, bslSourceSnoop

/* Sources valid for Appl layer */
#define BSL_SOURCE_APPL_VALID_INIT { \
    bslSourceRstp, \
    bslSourceSnoop, \
    bslSourceCount \
}

/* Short hand macros for Fsal layer */
#define BSL_FSAL_AUTH                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceAuth
#define BSL_FSAL_CFP                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceCfp
#define BSL_FSAL_COMMON                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceCommon
#define BSL_FSAL_COSQ                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceCosq
#define BSL_FSAL_L2                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceL2
#define BSL_FSAL_LAG                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceLag
#define BSL_FSAL_LINK                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceLink
#define BSL_FSAL_MCAST                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceMcast
#define BSL_FSAL_METER                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceMeter
#define BSL_FSAL_MIRROR                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceMirror
#define BSL_FSAL_OTHER                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceOther
#define BSL_FSAL_PKTIO                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourcePktio
#define BSL_FSAL_PORT                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourcePort
#define BSL_FSAL_STAT                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceStat
#define BSL_FSAL_STG                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceStg
#define BSL_FSAL_SWITCH                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceSwitch
#define BSL_FSAL_VLAN                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerFsal, bslSourceVlan

/* Sources valid for Fsal layer */
#define BSL_SOURCE_FSAL_VALID_INIT { \
    bslSourceLag, \
    bslSourceMirror, \
    bslSourcePort, \
    bslSourceLink, \
    bslSourceStg, \
    bslSourceOther, \
    bslSourceSwitch, \
    bslSourceL2, \
    bslSourceCommon, \
    bslSourceMeter, \
    bslSourceMcast, \
    bslSourcePktio, \
    bslSourceCfp, \
    bslSourceStat, \
    bslSourceVlan, \
    bslSourceCosq, \
    bslSourceAuth, \
    bslSourceCount \
}

/* Short hand macros for Sal layer */
#define BSL_SAL_COMMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSal, bslSourceCommon
#define BSL_SAL_OTHER                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSal, bslSourceOther

/* Sources valid for Sal layer */
#define BSL_SOURCE_SAL_VALID_INIT { \
    bslSourceOther, \
    bslSourceCommon, \
    bslSourceCount \
}

/* Short hand macros for Soc layer */
#define BSL_SOC_COMMON                  BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCommon
#define BSL_SOC_COUNTER                 BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCounter
#define BSL_SOC_CRAL                    BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceCral
#define BSL_SOC_L2                      BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceL2
#define BSL_SOC_OTHER                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceOther
#define BSL_SOC_PCI                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePci
#define BSL_SOC_PKTIO                   BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourcePktio
#define BSL_SOC_REG                     BSL_FILE, BSL_LINE, BSL_FUNC, bslLayerSoc, bslSourceReg

/* Sources valid for Soc layer */
#define BSL_SOURCE_SOC_VALID_INIT { \
    bslSourcePci, \
    bslSourceOther, \
    bslSourceL2, \
    bslSourceCommon, \
    bslSourcePktio, \
    bslSourceReg, \
    bslSourceCounter, \
    bslSourceCral, \
    bslSourceCount \
}

/* Organize layer/source/severity in a single 32-bit word */
#define BSL_LAYER_SHFT          24
#define BSL_LAYER_MASK          0xff
#define BSL_SOURCE_SHFT         8
#define BSL_SOURCE_MASK         0xffff
#define BSL_SEVERITY_SHFT       0
#define BSL_SEVERITY_MASK       0xff

/* Get elements of packed meta data */
#define BSL_LAYER_GET(chk_) \
    (((chk_) >> BSL_LAYER_SHFT) & BSL_LAYER_MASK)
#define BSL_SOURCE_GET(chk_) \
    (((chk_) >> BSL_SOURCE_SHFT) & BSL_SOURCE_MASK)
#define BSL_SEVERITY_GET(chk_) \
    (((chk_) >> BSL_SEVERITY_SHFT) & BSL_SEVERITY_MASK)

/* Encode elements for packed meta data */
#define BSL_LAYER_ENC(layer_) \
    ((layer_) << BSL_LAYER_SHFT)
#define BSL_SOURCE_ENC(source_) \
    ((source_) << BSL_SOURCE_SHFT)
#define BSL_SEVERITY_ENC(severity_) \
    ((severity_) << BSL_SEVERITY_SHFT)

/* Severity defines for LOG_* macros */
#define BSL_FATAL               BSL_SEVERITY_ENC(bslSeverityFatal)
#define BSL_ERROR               BSL_SEVERITY_ENC(bslSeverityError)
#define BSL_WARN                BSL_SEVERITY_ENC(bslSeverityWarn)
#define BSL_INFO                BSL_SEVERITY_ENC(bslSeverityInfo)
#define BSL_VERBOSE             BSL_SEVERITY_ENC(bslSeverityVerbose)
#define BSL_DEBUG               BSL_SEVERITY_ENC(bslSeverityDebug)

/* Layer defines for LOG_* macros */
#define BSL_L_APPL              BSL_LAYER_ENC(bslLayerAppl)
#define BSL_L_FSAL              BSL_LAYER_ENC(bslLayerFsal)
#define BSL_L_SAL               BSL_LAYER_ENC(bslLayerSal)
#define BSL_L_SOC               BSL_LAYER_ENC(bslLayerSoc)

/* Source defines for LOG_* macros */
#define BSL_S_AUTH              BSL_SOURCE_ENC(bslSourceAuth)
#define BSL_S_CFP               BSL_SOURCE_ENC(bslSourceCfp)
#define BSL_S_COMMON            BSL_SOURCE_ENC(bslSourceCommon)
#define BSL_S_COSQ              BSL_SOURCE_ENC(bslSourceCosq)
#define BSL_S_COUNTER           BSL_SOURCE_ENC(bslSourceCounter)
#define BSL_S_CRAL              BSL_SOURCE_ENC(bslSourceCral)
#define BSL_S_L2                BSL_SOURCE_ENC(bslSourceL2)
#define BSL_S_LAG               BSL_SOURCE_ENC(bslSourceLag)
#define BSL_S_LINK              BSL_SOURCE_ENC(bslSourceLink)
#define BSL_S_MCAST             BSL_SOURCE_ENC(bslSourceMcast)
#define BSL_S_METER             BSL_SOURCE_ENC(bslSourceMeter)
#define BSL_S_MIRROR            BSL_SOURCE_ENC(bslSourceMirror)
#define BSL_S_OTHER             BSL_SOURCE_ENC(bslSourceOther)
#define BSL_S_PCI               BSL_SOURCE_ENC(bslSourcePci)
#define BSL_S_PKTIO             BSL_SOURCE_ENC(bslSourcePktio)
#define BSL_S_PORT              BSL_SOURCE_ENC(bslSourcePort)
#define BSL_S_REG               BSL_SOURCE_ENC(bslSourceReg)
#define BSL_S_RSTP              BSL_SOURCE_ENC(bslSourceRstp)
#define BSL_S_SNOOP             BSL_SOURCE_ENC(bslSourceSnoop)
#define BSL_S_STAT              BSL_SOURCE_ENC(bslSourceStat)
#define BSL_S_STG               BSL_SOURCE_ENC(bslSourceStg)
#define BSL_S_SWITCH            BSL_SOURCE_ENC(bslSourceSwitch)
#define BSL_S_VLAN              BSL_SOURCE_ENC(bslSourceVlan)

/* Combined layer/sources for Appl layer */
#define BSL_LS_APPL_RSTP                (BSL_L_APPL | BSL_S_RSTP)
#define BSL_LS_APPL_SNOOP               (BSL_L_APPL | BSL_S_SNOOP)

/* Combined layer/sources for Fsal layer */
#define BSL_LS_FSAL_AUTH                (BSL_L_FSAL | BSL_S_AUTH)
#define BSL_LS_FSAL_CFP                 (BSL_L_FSAL | BSL_S_CFP)
#define BSL_LS_FSAL_COMMON              (BSL_L_FSAL | BSL_S_COMMON)
#define BSL_LS_FSAL_COSQ                (BSL_L_FSAL | BSL_S_COSQ)
#define BSL_LS_FSAL_L2                  (BSL_L_FSAL | BSL_S_L2)
#define BSL_LS_FSAL_LAG                 (BSL_L_FSAL | BSL_S_LAG)
#define BSL_LS_FSAL_LINK                (BSL_L_FSAL | BSL_S_LINK)
#define BSL_LS_FSAL_MCAST               (BSL_L_FSAL | BSL_S_MCAST)
#define BSL_LS_FSAL_METER               (BSL_L_FSAL | BSL_S_METER)
#define BSL_LS_FSAL_MIRROR              (BSL_L_FSAL | BSL_S_MIRROR)
#define BSL_LS_FSAL_OTHER               (BSL_L_FSAL | BSL_S_OTHER)
#define BSL_LS_FSAL_PKTIO               (BSL_L_FSAL | BSL_S_PKTIO)
#define BSL_LS_FSAL_PORT                (BSL_L_FSAL | BSL_S_PORT)
#define BSL_LS_FSAL_STAT                (BSL_L_FSAL | BSL_S_STAT)
#define BSL_LS_FSAL_STG                 (BSL_L_FSAL | BSL_S_STG)
#define BSL_LS_FSAL_SWITCH              (BSL_L_FSAL | BSL_S_SWITCH)
#define BSL_LS_FSAL_VLAN                (BSL_L_FSAL | BSL_S_VLAN)

/* Combined layer/sources for Sal layer */
#define BSL_LS_SAL_COMMON               (BSL_L_SAL | BSL_S_COMMON)
#define BSL_LS_SAL_OTHER                (BSL_L_SAL | BSL_S_OTHER)

/* Combined layer/sources for Soc layer */
#define BSL_LS_SOC_COMMON               (BSL_L_SOC | BSL_S_COMMON)
#define BSL_LS_SOC_COUNTER              (BSL_L_SOC | BSL_S_COUNTER)
#define BSL_LS_SOC_CRAL                 (BSL_L_SOC | BSL_S_CRAL)
#define BSL_LS_SOC_L2                   (BSL_L_SOC | BSL_S_L2)
#define BSL_LS_SOC_OTHER                (BSL_L_SOC | BSL_S_OTHER)
#define BSL_LS_SOC_PCI                  (BSL_L_SOC | BSL_S_PCI)
#define BSL_LS_SOC_PKTIO                (BSL_L_SOC | BSL_S_PKTIO)
#define BSL_LS_SOC_REG                  (BSL_L_SOC | BSL_S_REG)

#define BSL_SOURCES_VALID_DEF(type_) \
static type_ bsl_source_appl_valid[] = BSL_SOURCE_APPL_VALID_INIT; \
static type_ bsl_source_fsal_valid[] = BSL_SOURCE_FSAL_VALID_INIT; \
static type_ bsl_source_sal_valid[] = BSL_SOURCE_SAL_VALID_INIT; \
static type_ bsl_source_soc_valid[] = BSL_SOURCE_SOC_VALID_INIT


#define BSL_SOURCES_VALID_INIT { \
    bsl_source_appl_valid, \
    bsl_source_fsal_valid, \
    bsl_source_sal_valid, \
    bsl_source_soc_valid, \
    NULL \
}

#endif /* __SHR_BSLENUM_H__ */
