/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * $ID: $
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved$
 */

#ifndef __CDK_DEVIDS_H__
#define __CDK_DEVIDS_H__

#include <cdk_config.h>
#if 0
/*
 * Device Architecture Definitions
 */

#define CDK_DEV_ARCH_ROBO                    0x01
#define CDK_DEV_ARCH_XGS                     0x02
#define CDK_DEV_ARCH_SBX                     0x04
#define CDK_DEV_ARCH_XGSM                    0x08
#define CDK_DEV_ARCH_XGSD                    0x10
#define CDK_DEV_ARCH_MASK                    0x1f

/*
 * All Supported Devices and Revisions
 */

#define BROADCOM_VENDOR_ID                0x14e4
#define BROADCOM_PHYID_MSB                0x0143

/* BCM53158 */
#define BCM53158_VENDOR_ID                0xae02
#define BCM53158_DEVICE_ID                0x5100
#define BCM53158_REV_A0                     0x00


/* BCM53159 */
#define BCM53159_VENDOR_ID                0xae02
#define BCM53159_DEVICE_ID                0x5100
#define BCM53159_REV_A0                     0x00
/*
 * End of Supported Devices and Revisions
 */

#endif /* __CDK_DEVIDS_H__ */

#ifdef CDK_DEVLIST_ENTRY
/*
 * CDK_DEVLIST_ENTRY MACROS
 * 
 * Before including this file, define CDK_DEVLIST_ENTRY
 * as a macro to operate on the following parameters:
 *     #define CDK_DEVLIST_ENTRY(_nm,_vn,_dv,_rv,_md,_pi,_bd,_bc,_fn,_fl,_cn,_pf,_pd,_r0,_r1)
 * 
 *     _nm: Chip Name
 *     _vn: Chip Vendor ID
 *     _dv: Chip Device ID
 *     _rv: Chip Revision
 *     _md: Chip Model
 *     _pi: Probe Information
 *     _bd: SW Base Driver
 *     _bc: SW Base Configuration
 *     _fn: SW Full Name
 *     _fl: Flags
 *     _cn: Code Name
 *     _pf: Product Full Name
 *     _pd: Product Description
 *     _r0: Reserved
 *     _r1: Reserved
 * 
 * Note that this macro will be undefined at the end of this file.
 */

#endif
#endif

#if CDK_CONFIG_INCLUDE_BCM53158_A0 == 1
CDK_DEVLIST_ENTRY(BCM53158, BCM53158_VENDOR_ID, BCM53158_DEVICE_ID, BCM53158_REV_A0, \
                  0, 0, \
                  bcm53158_a0, bcm53158_a0, bcm53158_a0, \
                  CDK_DEV_ARCH_ROBO, "Avenger", "BCM53158", \
                  "16-Port GE Switch ", 0, 0)
#endif

#if CDK_CONFIG_INCLUDE_BCM53159_A0 == 1
CDK_DEVLIST_ENTRY(BCM53159, BCM53159_VENDOR_ID, BCM53159_DEVICE_ID, BCM53159_REV_A0, \
                  0, 0, \
                  bcm53159_a0, bcm53159_a0, bcm53159_a0, \
                  CDK_DEV_ARCH_ROBO, "Avenger", "BCM53159", \
                  "16-Port GE Switch ", 0, 0)
#endif

#endif
#endif
/* End CDK_DEVLIST_ENTRY Macros */

#ifdef CDK_DEVLIST_INCLUDE_ALL
#undef CDK_DEVLIST_INCLUDE_ALL
#endif
#undef CDK_DEVLIST_ENTRY
#endif /* CDK_DEVLIST_ENTRY */

