/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved.$
 *
 * File:	allmems.c
 * Purpose:	Independent memory descriptions.
 */

#include <soc/types.h>
#include <soc/robo2/common/allenum.h>
#include <soc/robo2/common/intenum.h>
#include <soc/robo2/common/memregs.h>
#include <soc/mem.h>

/*
 * This array is indexed by soc_mem_int_t; it describes all versions of
 * memories for all chips.  Chip memory arrays index into this summary.
 */
__attribute__((section("rdb.mems")))
soc_mem_info_t soc_robo2_mem_list[] = {
    { 0 } /* Extra empty entry for compiler */

}; /* soc_robo2_mem_list array */


/*
 * The arrays soc_mem_name, soc_mem_alias and soc_mem_desc are indexed
 * by soc_mem_t like the chip specific memory arrays.
 */
#if !defined(SOC_NO_NAMES)
__attribute__((section("rdb.memnames")))
char *soc_robo2_mem_name[] = {
    "" /* Extra null entry for compiler */
}; /* soc_robo2_mem_name array */
#endif /* !defined(SOC_NO_NAMES) */

#if !defined(SOC_NO_NAMES)
__attribute__((section("rdb.memnames")))
char *soc_robo2_mem_ufname[] = {
    "" /* Extra null entry for compiler */
}; /* soc_robo2_mem_ufname array */
#endif /* !defined(SOC_NO_NAMES) */

#if !defined(SOC_NO_ALIAS)
__attribute__((section("rdb.memalias")))
char *soc_robo2_mem_ufalias[] = {
    "" /* Extra null entry for compiler */
}; /* soc_robo2_mem_ufalias array */
#endif /* !defined(SOC_NO_ALIAS) */

#if !defined(SOC_NO_DESC)
__attribute__((section("memdesc")))
char *soc_robo2_mem_desc[] = {
    "" /* Extra null entry for compiler */
}; /* soc_robo2_mem_desc array */
#endif /* !defined(SOC_NO_DESC) */
