/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved.$
 *
 * File:	chip.c
 * Purpose:	Chip driver table defined
 * Supports:	bcm53158_b0
 *		bcm53158_a0
 */


#include <soc/defs.h>
#include <soc/robo2/common/driver.h>

/*
 * A null driver to indicate a given chip is not supported.
 *
 * This assumes that the chip is identified by device/rev id
 * and this will be 0 for the null driver, thus not match.
 */
#if !defined(BCM_53158_B0)  || !defined(BCM_53158_A0)
static soc_driver_t soc_driver_none;
#endif
/*
 * The table of all known drivers
 * Indexed by supported chips
 */
soc_driver_t *soc_robo2_base_driver_table[] = {


#if defined(BCM_53158_B0) || defined(BCM_53158_B1)
    &soc_driver_bcm53158_b0,
#else
    &soc_driver_none,
#endif

#if defined(BCM_53158_A0)
    &soc_driver_bcm53158_a0,
#else
    &soc_driver_none,
#endif

};

/* Function to translate SOC_CHIP_ to supported idx*/
int soc_robo2_chip_type_to_index(soc_chip_types chip)
{
    switch(chip) {
    case SOC_CHIP_BCM53158_B0:  return 0;
    case SOC_CHIP_BCM53158_B1:  return 0;
    case SOC_CHIP_BCM53158_A0:  return 1;
    default:  SAL_ASSERT(0);
    }
    return -1;
}

/* Reverse translation of above. */
soc_chip_types soc_robo2_index_to_chip_type(int chip)
{
    switch(chip) {
    case 0: return SOC_CHIP_BCM53158_B0;
    case 1: return SOC_CHIP_BCM53158_A0;
    case 2: return SOC_CHIP_BCM53158_B0;
    default:  SAL_ASSERT(0);
    }
    return -1;
}

