/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * $Copyright: (c) 2017 Broadcom Corp.
 * All Rights Reserved.$
 *
 * File:	driver.h
 * Purpose:	Chip driver declarations
 * Supports:	bcm53158_b0
 *		bcm53158_a0
 */

#ifndef _SOC_ROBO2_DRIVER_H
#define _SOC_ROBO2_DRIVER_H


#include <soc/drv.h>

/****************************************************************
 *
 *    Chip driver declarations
 *
 ****************************************************************/

EXTERN soc_driver_t soc_driver_bcm53158_b0;
EXTERN soc_driver_t soc_driver_bcm53158_a0;
#ifdef ETH_MII_DEBUG
EXTERN soc_driver_t soc_driver_bcm4713_a0;
#endif
/* The table of all known drivers */
/* Indexed by supported chips */
EXTERN soc_driver_t *soc_robo2_base_driver_table[SOC_ROBO2_NUM_SUPPORTED_CHIPS];

EXTERN int soc_robo2_chip_type_to_index(soc_chip_types chip);
EXTERN soc_chip_types soc_robo2_index_to_chip_type(int chip);


#endif	/* !_SOC_ROBO2_DRIVER_H */
