/* * $ID: $
 * * $Copyright: (c) 2017 Broadcom Corp.
 * * All Rights Reserved$
 * *
 * * File:
 * *     port_capab.c
 * *
 * */

#include <stdbool.h>
#include "osal/sal_types.h"
#include "shared/types.h"
#include "shared/portdb.h"
#include "app.h"
#include "port_capab.h"


/* BOARD_BCM53156 
   Ports 0-7    : 10/100/1000 Base-T (GPHY)
   Ports 8-11   : n/a
   Ports 12     : 10G (XFI) - only 1
*/
#ifdef BOARD_BCM53156

uint32_t port_capab[] = {
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX | PORT_CAPAB_HDX
};

#endif // BOARD_BCM53156

/* BOARD_BCM53162
   Ports 0-7    : 10/100/1000 Base-T (GPHY)
   Ports 8-11   : SGMII+
   Ports 12-13  : 10G (XFI)
*/
#ifdef BOARD_BCM53162

uint32_t port_capab[] = {
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX
};

#endif // BOARD_BCM53162

/* BOARD_BCM53162_CASCADE
   Ports 0-6    : 10/100/1000 Base-T (GPHY)
   Port 3       : Cascade Link (excluded)
   Ports 7-10   : 100/1000/2500 (SGMII+)
   Ports 11-12  : 10G (XFI)
   Ports 13-19  : 10/100/1000 Base-T (GPHY)
   Port 16      : Cascade Link (excluded)
   Ports 20-23  : 100/1000/2500 (SGMII+)
   Ports 24-25  : 10G (XFI)
*/
#ifdef BOARD_BCM53162_CASCADE

uint32_t port_capab[] = {
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX
};

#endif // BOARD_BCM53162_CASCADE

/* BOARD_BCM53158 
   Ports 0-7    : 10/100/1000 Base-T (GPHY)
   Ports 8-11   : (QSGMII)
   Ports 12-13  : 10G (XFI)
*/
#ifdef BOARD_BCM53158

uint32_t port_capab[] = {
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX
};

#endif // BOARD_BCM53158

/* BOARD_BCM53112 
   Ports 0-7    : 10/100/1000 Base-T (GPHY)
   Ports 8-11   : SGMII+
   Ports 12-13  : SGMII+
*/
#ifdef BOARD_BCM53112

uint32_t port_capab[] = {
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_GPHY | PORT_CAPAB_SPEED_10M | PORT_CAPAB_SPEED_100M | PORT_CAPAB_SPEED_1000M | PORT_CAPAB_AUTONEG | PORT_CAPAB_FDX | PORT_CAPAB_HDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX,
  PORT_CAPAB_SGMII | PORT_CAPAB_SPEED_2500M | PORT_CAPAB_FDX
};

#endif // BOARD_BCM53112

/* BOARD_BCM53161 
   Ports 0-7    : n/a
   Ports 8-11   : SGMII+
   Ports 12-13  : XFI
*/
#ifdef BOARD_BCM53161

uint32_t port_capab[] = {
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_QSGMII | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX,
  PORT_CAPAB_XFI | PORT_CAPAB_SPEED_10G | PORT_CAPAB_FDX
};

#endif // BOARD_BCM53161

#ifdef WEB_SERVER_SIM

int portdb_uport_capab_get(uint8_t uport_idx, uint32_t *capab) {
  uint8_t count = portdb_uport_phys_count_get();
  uint8_t idx; 

  if (count == 0) {
    return APP_E_INTERNAL;
  }
  idx = uport_idx - ((uint8_t) portdb_uport_phys_first_get());
  *capab = port_capab[idx];
  return APP_E_NONE;
}

int portdb_uport_phys_type_get(uint8_t uport_idx, uint32_t *phys_type)
{
    int      rv;
    uint32_t attrib;

    rv = portdb_uport_capab_get(uport_idx, &attrib);
    if (rv == 0) {
        if (attrib & PORT_CAPAB_GPHY) {
            *phys_type = PORT_CAPAB_GPHY;
        } else if (attrib & PORT_CAPAB_SGMII) {
            *phys_type = PORT_CAPAB_SGMII;
        } else if (attrib & PORT_CAPAB_QSGMII) {
            *phys_type = PORT_CAPAB_QSGMII;
        } else if (attrib & PORT_CAPAB_XFI) {
            *phys_type = PORT_CAPAB_XFI;
        } else {
            rv = -1;
        }
    }
    return rv;
}

#endif // WEB_SERVER_SIM
